---
language: generic

sudo: required

services:
  - docker

before_install:
  - docker pull vrutkovs/flatpak

script:
  - git clone -b gh-pages https://github.com/vrutkovs/flatpaks export/ && cp -rf export/repo . || mkdir export
  - docker run --privileged -v ${PWD}:/source --name flatpak -i vrutkovs/flatpak make -C source
  - rm -rf export && mkdir export
  - cp -rf repo/ export/
  - cp -rf firefox.flatpakref export/

notifications:
  webhooks: https://hubot.vrutkovs.eu/travis-ci/103761953

deploy:
  provider: pages
  local_dir: export
  skip_cleanup: true
  repo: vrutkovs/flatpaks
  github_token: $GITHUB_TOKEN
  on:
    branch: binaries
